#!/bin/bash
function drupalgap_install() {
  mkdir node_modules
  cd node_modules/
  mkdir angular-drupal
  cd angular-drupal/
  mkdir build
  cd build/
  wget https://raw.githubusercontent.com/easystreet3/angular-drupal/7.x-1.x/build/angular-drupal.min.js --no-check-certificate
  cd ../../../app/
  mkdir bower_components
  cd bower_components/
  mkdir jquery
  cd jquery/
  mkdir dist
  cd dist/
  wget http://code.jquery.com/jquery-2.1.1.min.js
  mv jquery-2.1.1.min.js jquery.js
  cd ../../
  mkdir angular
  cd angular/
  wget https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js
  mv angular.min.js angular.js
  cd ../
  mkdir angular-animate
  cd angular-animate/
  wget https://code.angularjs.org/1.4.2/angular-animate.min.js
  mv angular-animate.min.js angular-animate.js
  cd ../
  mkdir angular-route
  cd angular-route/
  wget https://code.angularjs.org/1.4.2/angular-route.min.js
  mv angular-route.min.js angular-route.js
  cd ../
  mkdir angular-resource
  cd angular-resource/
  wget https://code.angularjs.org/1.4.2/angular-resource.min.js
  mv angular-resource.min.js angular-resource.js
  cd ../
  mkdir angular-sanitize
  cd angular-sanitize/
  wget https://code.angularjs.org/1.4.2/angular-sanitize.min.js
  mv angular-sanitize.min.js angular-sanitize.js
  cd ../
  mkdir bootstrap
  cd bootstrap/
  mkdir dist
  cd dist/
  mkdir css
  cd css/
  wget https://maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
  mv bootstrap.min.css bootstrap.css
}
case "$1" in
-a|-A) echo you picked A;;
-b|-B) echo you picked B;;
-c|-C) echo you picked C;;
install) drupalgap_install;;
-*) usage "bad argument $1";;
esac
